<section class="text-light bg-dark p-5 text-center text-sm-start">
  <div class="container">
    <div class="">
      <h1 class="mt-2 text-center">Terms of Services</h1>
    </div>
  </div>
</section>

<section class="features-main pb-5 pt-5 bg-secondary">

  <div class="container grid grid-3 align-items-center">

    <div class="card text-dark mb-3" style="background-color:#eee;">
      <div class="card-header">
        <h6></h6>
      </div>
      <div class="card-body my-2 px-5">
        <h5 class="card-title"><strong>General Terms</strong></h5>
        <hr>
        <p class="card-text ps-3">By accessing, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and
          Under no circumstances shall team be liable for any direct, indirect, special, incidental or consequential damages, including, but not Limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.
          will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to remove posts and notes that violate the terms and policy at any moment without any notice.</p>
      </div>
    </div>

    <div class="card text-dark mb-3" style="background-color:#eee;">
      <div class="card-header">
        <h6></h6>
      </div>
      <div class="card-body my-2 px-5">
        <h5 class="card-title"><strong>License</strong></h5>
        <hr>
        <p class="card-text ps-3">Virtual diary grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use our service strictly in accordance with the terms of this Agreement.
          These Terms & Conditions are a contract between you and virtual diary (referred to in these Terms & Conditions as "virtual diary" "us", "we" or "our"), the provider of the virtual diary website and the services accessible from the virtual diary website (which are collectively referred to in these Terms & Conditions as the "virtual diary Service").
          You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use the Service. In these Terms & Conditions, "you" refers both to you as an individual and to the entity you represent. If you violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to your account without notice.
        </p>
      </div>
    </div>

    <div class="card text-dark mb-3" style="background-color:#eee;">
      <div class="card-header">
        <h6></h6>
      </div>
      <div class="card-body my-2 px-5">
        <h5 class="card-title"><strong>Definitions and Key Terms</strong></h5>
        <hr>
        <p class="card-text ps-3">For this Terms & Conditions:
          <ul>
            <li>Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information. </li>
            <li>Company: when this policy mentions "Company," "we," "us," or "our," it refers to Virtual Diary, Philippines that is responsible for your information under this Privacy Policy. </li>
            <li>Country: where virtual diary or the owners/founders of virtual diary are based in this case is Philippines. </li>
            <li>user refers to the company, organization or person that signs up to use the virtual diary Service to manage the relationships with your consumers or service users. </li>
            <li>Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit virtual
              diary and use the services. IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet. </li>
            <li>Personnel: refers to those individuals who are employed by virtual diary or are under contract to perform a service on behalf
              of one of the parties. </li>
            <li>Personal Data: any information that directly, indirectly, or in connection with other information — including a personal
              umber — allows for the identification or identifiability of a natural person. </li>
            <li>Service: refers to the service provided by virtual diary as described in the relative terms (if available) and on this platform. </li>
            <li>Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our
              content or whose products/services we think may interest you. </li>
            <li>Website: virtual diary's site, which can be accessed via this URL: www.virtual-diary.com. </li>
            <li>You: a person or entity that is registered with virtual diary to use the Services.</li>
          </ul>
        </p>
      </div>
    </div>

    <div class="card text-dark mb-3" style="background-color:#eee;">
      <div class="card-header">
        <h6></h6>
      </div>
      <div class="card-body my-2 px-5">
        <h5 class="card-title"><strong>Restrictions</strong></h5>
        <hr>
        <p class="card-text ps-3">You agree not to, and you will not permit others to:
          <ul>
            <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the service or
              make the platform available to any third party</li>
            <li>Modify, make derivative works of disassemble, decrypt, reverse compile or reverse engineer any part of the service. </li>
            <li>Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of or its affiliates, partners,
              suppliers or the licensors of the service.</li>
          </ul>
        </p>
      </div>
    </div>

    <div class="card text-dark mb-3" style="background-color:#eee;">
      <div class="card-header">
        <h6></h6>
      </div>
      <div class="card-body my-2 px-5">
        <h5 class="card-title"><strong>Your Suggestions</strong></h5>
        <hr>
        <p class="card-text ps-3">Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions") provided by you to us with respect to the service shall remain the sole and exclusive property of us. We shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.
        </p>
      </div>
    </div>

    <div class="card text-dark mb-3" style="background-color:#eee;">
      <div class="card-header">
        <h6></h6>
      </div>
      <div class="card-body my-2 px-5">
        <h5 class="card-title"><strong>Your Consent</strong></h5>
        <hr>
        <p class="card-text ps-3">We've updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our service, registering an account, you hereby consent to our Terms & Conditions.
        </p>
      </div>
    </div>

    <div class="card text-dark mb-3" style="background-color:#eee;">
      <div class="card-header">
        <h6></h6>
      </div>
      <div class="card-body my-2 px-5">
        <h5 class="card-title"><strong>Links to Other Websites</strong></h5>
        <hr>
        <p class="card-text ps-3">Our service may contain links to other websites that are not operated by Us. If you click on a third party link, You will be directed to that third party's site. We strongly advise you to review the Terms & Conditions of every site you visit. We have no control over and assume no responsibility for the content, Terms & Conditions or practices of any third party sites or services
        </p>
      </div>
    </div>

    <div class="card text-dark mb-3" style="background-color:#eee;">
      <div class="card-header">
        <h6></h6>
      </div>
      <div class="card-body my-2 px-5">
        <h5 class="card-title"><strong>Cookies</strong></h5>
        <hr>
        <p class="card-text ps-3">We use "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use cookies to enhance the performance and functionality of our service but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit our platform as we would not be able to remember that you had Logged in previously. Most web browsers can be set to disable the use of cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.
        </p>
      </div>
    </div>

    <div class="card text-dark mb-3" style="background-color:#eee;">
      <div class="card-header">
        <h6></h6>
      </div>
      <div class="card-body my-2 px-5">
        <h5 class="card-title"><strong>Changes To Our Terms & Conditions</strong></h5>
        <hr>
        <p class="card-text ps-3">You acknowledge and agree that we may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at our sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform us when you stop using the Service. You acknowledge and agree that if we disable access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which is contained in your account. If we decide to change our Terms & Conditions, we will post those changes on this page, and/or update the Terms & Conditions modification date below.
        </p>
      </div>
    </div>

    <div class="card text-dark mb-3" style="background-color:#eee;">
      <div class="card-header">
        <h6></h6>
      </div>
      <div class="card-body my-2 px-5">
        <h5 class="card-title"><strong>Modifications to Our Service</strong></h5>
        <hr>
        <p class="card-text ps-3">We reserve the right to modify, suspend or discontinue, temporarily or permanently, the service or any service to which it connects, with or without notice and without liability to you.
        </p>
      </div>
    </div>

    <div class="card text-dark mb-3" style="background-color:#eee;">
      <div class="card-header">
        <h6></h6>
      </div>
      <div class="card-body my-2 px-5">
        <h5 class="card-title"><strong>Updates to Our Service</strong></h5>
        <hr>
        <p class="card-text ps-3">We may from time to time provide enhancements or improvements to the features/functionality of the service, which may include patches, bug fixes, updates, upgrades and other modifications ("Updates"). Updates may modify or delete certain features and/or functionalities of the service. You agree that we have no obligation to provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the service to you. You further agree that all Updates will be (i) deemed to constitute an integral part of the service, and (ii) subject to the terms and conditions of this Agreement.
        </p>
      </div>
    </div>

    <div class="card text-dark mb-3" style="background-color:#eee;">
      <div class="card-header">
        <h6></h6>
      </div>
      <div class="card-body my-2 px-5">
        <h5 class="card-title"><strong>Updates to Our Terms</strong></h5>
        <hr>
        <p class="card-text ps-3">We may change our Service and policies, and we may need to make changes to these Terms so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to these Terms and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Terms. If you do not want to agree to these or any updated Terms, you can delete your account
        </p>
      </div>
    </div>

    <div class="card text-dark mb-3" style="background-color:#eee;">
      <div class="card-header">
        <h6></h6>
      </div>
      <div class="card-body my-2 px-5">
        <h5 class="card-title"><strong>Intellectual Property</strong></h5>
        <hr>
        <p class="card-text ps-3">Our platform and its entire contents, features and functionality (including but not limited to all information, software, text, displays, images, video and audio, and the design, selection and arrangement thereof), are owned by us, its licensors or other providers of such material and are protected by and international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws. The material may not be copied, modified, reproduced, downloaded or distributed in any way, in whole or in part, without the express prior written permission of us, unless and except as is expressly provided in these Terms & Conditions. Any unauthorized use of the material is prohibited.
        </p>
      </div>
    </div>

    <div class="card text-dark mb-3" style="background-color:#eee;">
      <div class="card-header">
        <h6></h6>
      </div>
      <div class="card-body my-2 px-5">
        <h5 class="card-title"><strong>Agreement to Arbitrate</strong></h5>
        <hr>
        <p class="card-text ps-3">This section applies to any dispute EXCEPT IT DOESN'T INCLUDE A DISPUTE RELATING TO CLAIMS FOR INJUNCTIVE OR EQUITABLE RELIEF REGARDING THE ENFORCEMENT OR VALIDITY OF YOUR OR'S INTELLECTUAL PROPERTY RIGHTS. The term "dispute" means any dispute, action, or other controversy between you and us concerning the Services or this agreement, whether in contract, warranty, tort, statute, regulation, ordinance, or any other legal or equitable basis. “Dispute" will be given the broadest possible meaning allowable under law.
        </p>
      </div>
    </div>

    <div class="card text-dark mb-3" style="background-color:#eee;">
      <div class="card-header">
        <h6></h6>
      </div>
      <div class="card-body my-2 px-5">
        <h5 class="card-title"><strong>Notice of Dispute</strong></h5>
        <hr>
        <p class="card-text ps-3">In the event of a dispute, you or us must give the other a Notice of Dispute, which is a written statement that sets forth the name, address, and contact information of the party giving it, the facts giving rise to the dispute, and the relief requested. You must send any Notice of Dispute via email to: We will send any Notice of Dispute to you by mail to your address if we have it, or otherwise to your email address. You and us will attempt to resolve any dispute through informal negotiation within sixty (60) days from the date the Notice of Dispute is sent. After sixty (60) days, you or us may commence arbitration.
        </p>
      </div>
    </div>

    <div class="card text-dark mb-3" style="background-color:#eee;">
      <div class="card-header">
        <h6></h6>
      </div>
      <div class="card-body my-2 px-5">
        <h5 class="card-title"><strong>Binding Arbitration</strong></h5>
        <hr>
        <p class="card-text ps-3">If you and us don't resolve any dispute by informal negotiation, any other effort to resolve the dispute will be conducted exclusively by binding arbitration as described in this section. You are giving up the right to litigate (or participate in as a party or class member) all disputes in court before a judge or jury. The dispute shall be settled by binding arbitration in accordance with the commercial arbitration rules of the American Arbitration Association. Either party may seek any interim or preliminary injunctive relief from any court of competent jurisdiction, as necessary to protect the party's rights or property pending the completion of arbitration. Any and all legal, accounting, and other costs, fees, and expenses incurred by the prevailing party shall be borne by the non-prevailing party.
        </p>
      </div>
    </div>

    <div class="card text-dark mb-3" style="background-color:#eee;">
      <div class="card-header">
        <h6></h6>
      </div>
      <div class="card-body my-2 px-5">
        <h5 class="card-title"><strong>Submissions and Privacy</strong></h5>
        <hr>
        <p class="card-text ps-3">In the event that you submit or post any ideas, creative suggestions, designs, photographs, information, advertisements, data or proposals, including ideas for new or improved products, services, features, technologies or promotions, you expressly agree that such submissions will automatically be treated as non-confidential and non-proprietary and will become the sole property of us without any compensation or credit to you whatsoever. We and our affiliates shall have no obligations with respect to such submissions or posts and may use the ideas contained in such submissions or posts for any purposes in any medium in perpetuity, including, but not limited to, developing, manufacturing, and marketing products and services using such ideas.
        </p>
      </div>
    </div>

    <div class="card text-dark mb-3" style="background-color:#eee;">
      <div class="card-header">
        <h6></h6>
      </div>
      <div class="card-body my-2 px-5">
        <h5 class="card-title"><strong>Disclaimer</strong></h5>
        <hr>
        <p class="card-text ps-3">We are not responsible for any content, code or any other imprecision posted by the other users of this application. In no event shall we be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. We reserve the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.
          Our Service and its contents are provided as a way to represent expressions, idea, opinions and the like. We are a service provider on the social media space and not a publisher of the content supplied by users, as such, our exercises nor editorial control over such content and does not represent our team and application to such. No oral advice or written information given by us or any of its affiliates, employees, officers, directors, agents, or the like will create an excuse to be exempted. The application can undergo possible changes without prior notice for the betterment for both users and its providers, and we hope for an error-free environment in such space.
        </p>
      </div>
    </div>

    <div class="card text-dark mb-3" style="background-color:#eee;">
      <div class="card-header">
        <h6></h6>
      </div>
      <div class="card-body my-2 px-5">
        <h5 class="card-title"><strong>Contact Us</strong></h5>
        <hr>
        <p class="card-text ps-3">Don't hesitate to contact us if you have any questions.
        <ul>
          <li>Via Email: virtual.diary@gmail.com</li>
          <li>Via this Address: Ermita, Manila</li>
        </ul>
        </p>
      </div>
    </div>
  </div>
</section>

    <style>
      body {
        background-color: #eee;
      }

      .main {
        color: #000;
        margin: 0 auto;
      }

      .space {
        width: 600px;
        margin: 50px auto;
        padding: 0px;
      }
    </style>